### PR TITLE
Fix error reporting

### PR DESCRIPTION
**Pull request by matthid**
In Ionide I always only see "parsing failed" which seems to be the generic error for "something failed and we don't know what".

This PR is the first step in improving the situation. I have followed the error report to this code path:

https://github.com/fsharp/FsAutoComplete/blob/810016f9baf43dcedf9a78f2935a887767f356b5/src/FsAutoComplete.Core/Workspace.fs#L27

Which boils down to `GetProjectOptions` returning `None`.
There are endless variations where this can happen:
- Loading already failed and the notification was handled before -> None will "hide" the actual error (this PR fixes that by returning the "real" error from `lastProjectError`)
- Loading didn't even start because it is not a `.fsproj`
- Project somehow was never actually loaded (ie no error occurred and the result was not cached; I'm not sure if this can happen in practise but we will see)
- Probably others.

None besides the first is actually a "parsing failed" as reported.

Next step is to use these changes in FSAC to report better errors.

### CODE REVIEW

**Comment by cartermp** [comment]
Not sure if this reflects others' experiences, but the big one for me is manually adding something to the project file and forgetting the closing `/`.

**Comment by matthid** [comment]
Funnily, I didn't even edit any project files and most of them were shown as `parsing failed` which was quite surprising. After reloading the window everything loaded just fine, so next time with this I hope to get some better error ...

**Comment by enricosada** [comment]
Thanks @matthid i'll check later this week!

**Comment by matthid** [comment]
See https://github.com/enricosada/dotnet-proj-info/issues/59 this already found an issue :)

**Comment by enricosada** [comment]
Merged, thanks a lot @matthid !

**Pull request merged**
